// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "thread_messages", Type: field.TypeString, Nullable: true},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_threads_messages",
				Columns:    []*schema.Column{MessagesColumns[4]},
				RefColumns: []*schema.Column{ThreadsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ThreadsColumns holds the columns for the "threads" table.
	ThreadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "original_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "workspace_path", Type: field.TypeString},
		{Name: "source_file_path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_synced_at", Type: field.TypeTime},
	}
	// ThreadsTable holds the schema information for the "threads" table.
	ThreadsTable = &schema.Table{
		Name:       "threads",
		Columns:    ThreadsColumns,
		PrimaryKey: []*schema.Column{ThreadsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MessagesTable,
		ThreadsTable,
	}
)

func init() {
	MessagesTable.ForeignKeys[0].RefTable = ThreadsTable
}
