// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zuhailkhan/threadman/ent/message"
	"github.com/zuhailkhan/threadman/ent/predicate"
	"github.com/zuhailkhan/threadman/ent/thread"
)

// ThreadUpdate is the builder for updating Thread entities.
type ThreadUpdate struct {
	config
	hooks    []Hook
	mutation *ThreadMutation
}

// Where appends a list predicates to the ThreadUpdate builder.
func (_u *ThreadUpdate) Where(ps ...predicate.Thread) *ThreadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ThreadUpdate) SetProvider(v string) *ThreadUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableProvider(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *ThreadUpdate) SetOriginalID(v string) *ThreadUpdate {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableOriginalID(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ThreadUpdate) SetTitle(v string) *ThreadUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableTitle(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetWorkspacePath sets the "workspace_path" field.
func (_u *ThreadUpdate) SetWorkspacePath(v string) *ThreadUpdate {
	_u.mutation.SetWorkspacePath(v)
	return _u
}

// SetNillableWorkspacePath sets the "workspace_path" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableWorkspacePath(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetWorkspacePath(*v)
	}
	return _u
}

// SetSourceFilePath sets the "source_file_path" field.
func (_u *ThreadUpdate) SetSourceFilePath(v string) *ThreadUpdate {
	_u.mutation.SetSourceFilePath(v)
	return _u
}

// SetNillableSourceFilePath sets the "source_file_path" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableSourceFilePath(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetSourceFilePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ThreadUpdate) SetCreatedAt(v time.Time) *ThreadUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableCreatedAt(v *time.Time) *ThreadUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ThreadUpdate) SetLastSyncedAt(v time.Time) *ThreadUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableLastSyncedAt(v *time.Time) *ThreadUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ThreadUpdate) AddMessageIDs(ids ...string) *ThreadUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ThreadUpdate) AddMessages(v ...*Message) *ThreadUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_u *ThreadUpdate) Mutation() *ThreadMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ThreadUpdate) ClearMessages() *ThreadUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ThreadUpdate) RemoveMessageIDs(ids ...string) *ThreadUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ThreadUpdate) RemoveMessages(v ...*Message) *ThreadUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ThreadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ThreadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ThreadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(thread.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(thread.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(thread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkspacePath(); ok {
		_spec.SetField(thread.FieldWorkspacePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFilePath(); ok {
		_spec.SetField(thread.FieldSourceFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(thread.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(thread.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ThreadUpdateOne is the builder for updating a single Thread entity.
type ThreadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThreadMutation
}

// SetProvider sets the "provider" field.
func (_u *ThreadUpdateOne) SetProvider(v string) *ThreadUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableProvider(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *ThreadUpdateOne) SetOriginalID(v string) *ThreadUpdateOne {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableOriginalID(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ThreadUpdateOne) SetTitle(v string) *ThreadUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableTitle(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetWorkspacePath sets the "workspace_path" field.
func (_u *ThreadUpdateOne) SetWorkspacePath(v string) *ThreadUpdateOne {
	_u.mutation.SetWorkspacePath(v)
	return _u
}

// SetNillableWorkspacePath sets the "workspace_path" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableWorkspacePath(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetWorkspacePath(*v)
	}
	return _u
}

// SetSourceFilePath sets the "source_file_path" field.
func (_u *ThreadUpdateOne) SetSourceFilePath(v string) *ThreadUpdateOne {
	_u.mutation.SetSourceFilePath(v)
	return _u
}

// SetNillableSourceFilePath sets the "source_file_path" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableSourceFilePath(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetSourceFilePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ThreadUpdateOne) SetCreatedAt(v time.Time) *ThreadUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableCreatedAt(v *time.Time) *ThreadUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ThreadUpdateOne) SetLastSyncedAt(v time.Time) *ThreadUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableLastSyncedAt(v *time.Time) *ThreadUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ThreadUpdateOne) AddMessageIDs(ids ...string) *ThreadUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ThreadUpdateOne) AddMessages(v ...*Message) *ThreadUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_u *ThreadUpdateOne) Mutation() *ThreadMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ThreadUpdateOne) ClearMessages() *ThreadUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ThreadUpdateOne) RemoveMessageIDs(ids ...string) *ThreadUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ThreadUpdateOne) RemoveMessages(v ...*Message) *ThreadUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ThreadUpdate builder.
func (_u *ThreadUpdateOne) Where(ps ...predicate.Thread) *ThreadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ThreadUpdateOne) Select(field string, fields ...string) *ThreadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Thread entity.
func (_u *ThreadUpdateOne) Save(ctx context.Context) (*Thread, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadUpdateOne) SaveX(ctx context.Context) *Thread {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ThreadUpdateOne) sqlSave(ctx context.Context) (_node *Thread, err error) {
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Thread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thread.FieldID)
		for _, f := range fields {
			if !thread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != thread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(thread.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(thread.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(thread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkspacePath(); ok {
		_spec.SetField(thread.FieldWorkspacePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFilePath(); ok {
		_spec.SetField(thread.FieldSourceFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(thread.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(thread.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Thread{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
