// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zuhailkhan/threadman/ent/message"
	"github.com/zuhailkhan/threadman/ent/thread"
)

// ThreadCreate is the builder for creating a Thread entity.
type ThreadCreate struct {
	config
	mutation *ThreadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *ThreadCreate) SetProvider(v string) *ThreadCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetOriginalID sets the "original_id" field.
func (_c *ThreadCreate) SetOriginalID(v string) *ThreadCreate {
	_c.mutation.SetOriginalID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ThreadCreate) SetTitle(v string) *ThreadCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetWorkspacePath sets the "workspace_path" field.
func (_c *ThreadCreate) SetWorkspacePath(v string) *ThreadCreate {
	_c.mutation.SetWorkspacePath(v)
	return _c
}

// SetSourceFilePath sets the "source_file_path" field.
func (_c *ThreadCreate) SetSourceFilePath(v string) *ThreadCreate {
	_c.mutation.SetSourceFilePath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThreadCreate) SetCreatedAt(v time.Time) *ThreadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *ThreadCreate) SetLastSyncedAt(v time.Time) *ThreadCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ThreadCreate) SetID(v string) *ThreadCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ThreadCreate) AddMessageIDs(ids ...string) *ThreadCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ThreadCreate) AddMessages(v ...*Message) *ThreadCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_c *ThreadCreate) Mutation() *ThreadMutation {
	return _c.mutation
}

// Save creates the Thread in the database.
func (_c *ThreadCreate) Save(ctx context.Context) (*Thread, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThreadCreate) SaveX(ctx context.Context) *Thread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThreadCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Thread.provider"`)}
	}
	if _, ok := _c.mutation.OriginalID(); !ok {
		return &ValidationError{Name: "original_id", err: errors.New(`ent: missing required field "Thread.original_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Thread.title"`)}
	}
	if _, ok := _c.mutation.WorkspacePath(); !ok {
		return &ValidationError{Name: "workspace_path", err: errors.New(`ent: missing required field "Thread.workspace_path"`)}
	}
	if _, ok := _c.mutation.SourceFilePath(); !ok {
		return &ValidationError{Name: "source_file_path", err: errors.New(`ent: missing required field "Thread.source_file_path"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Thread.created_at"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "Thread.last_synced_at"`)}
	}
	return nil
}

func (_c *ThreadCreate) sqlSave(ctx context.Context) (*Thread, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Thread.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThreadCreate) createSpec() (*Thread, *sqlgraph.CreateSpec) {
	var (
		_node = &Thread{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(thread.Table, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(thread.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.OriginalID(); ok {
		_spec.SetField(thread.FieldOriginalID, field.TypeString, value)
		_node.OriginalID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(thread.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.WorkspacePath(); ok {
		_spec.SetField(thread.FieldWorkspacePath, field.TypeString, value)
		_node.WorkspacePath = value
	}
	if value, ok := _c.mutation.SourceFilePath(); ok {
		_spec.SetField(thread.FieldSourceFilePath, field.TypeString, value)
		_node.SourceFilePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(thread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(thread.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Thread.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadCreate) OnConflict(opts ...sql.ConflictOption) *ThreadUpsertOne {
	_c.conflict = opts
	return &ThreadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadCreate) OnConflictColumns(columns ...string) *ThreadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadUpsertOne{
		create: _c,
	}
}

type (
	// ThreadUpsertOne is the builder for "upsert"-ing
	//  one Thread node.
	ThreadUpsertOne struct {
		create *ThreadCreate
	}

	// ThreadUpsert is the "OnConflict" setter.
	ThreadUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *ThreadUpsert) SetProvider(v string) *ThreadUpsert {
	u.Set(thread.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateProvider() *ThreadUpsert {
	u.SetExcluded(thread.FieldProvider)
	return u
}

// SetOriginalID sets the "original_id" field.
func (u *ThreadUpsert) SetOriginalID(v string) *ThreadUpsert {
	u.Set(thread.FieldOriginalID, v)
	return u
}

// UpdateOriginalID sets the "original_id" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateOriginalID() *ThreadUpsert {
	u.SetExcluded(thread.FieldOriginalID)
	return u
}

// SetTitle sets the "title" field.
func (u *ThreadUpsert) SetTitle(v string) *ThreadUpsert {
	u.Set(thread.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateTitle() *ThreadUpsert {
	u.SetExcluded(thread.FieldTitle)
	return u
}

// SetWorkspacePath sets the "workspace_path" field.
func (u *ThreadUpsert) SetWorkspacePath(v string) *ThreadUpsert {
	u.Set(thread.FieldWorkspacePath, v)
	return u
}

// UpdateWorkspacePath sets the "workspace_path" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateWorkspacePath() *ThreadUpsert {
	u.SetExcluded(thread.FieldWorkspacePath)
	return u
}

// SetSourceFilePath sets the "source_file_path" field.
func (u *ThreadUpsert) SetSourceFilePath(v string) *ThreadUpsert {
	u.Set(thread.FieldSourceFilePath, v)
	return u
}

// UpdateSourceFilePath sets the "source_file_path" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateSourceFilePath() *ThreadUpsert {
	u.SetExcluded(thread.FieldSourceFilePath)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ThreadUpsert) SetCreatedAt(v time.Time) *ThreadUpsert {
	u.Set(thread.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateCreatedAt() *ThreadUpsert {
	u.SetExcluded(thread.FieldCreatedAt)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ThreadUpsert) SetLastSyncedAt(v time.Time) *ThreadUpsert {
	u.Set(thread.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateLastSyncedAt() *ThreadUpsert {
	u.SetExcluded(thread.FieldLastSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(thread.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ThreadUpsertOne) UpdateNewValues() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(thread.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ThreadUpsertOne) Ignore() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadUpsertOne) DoNothing() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadCreate.OnConflict
// documentation for more info.
func (u *ThreadUpsertOne) Update(set func(*ThreadUpsert)) *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ThreadUpsertOne) SetProvider(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateProvider() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateProvider()
	})
}

// SetOriginalID sets the "original_id" field.
func (u *ThreadUpsertOne) SetOriginalID(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetOriginalID(v)
	})
}

// UpdateOriginalID sets the "original_id" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateOriginalID() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateOriginalID()
	})
}

// SetTitle sets the "title" field.
func (u *ThreadUpsertOne) SetTitle(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateTitle() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateTitle()
	})
}

// SetWorkspacePath sets the "workspace_path" field.
func (u *ThreadUpsertOne) SetWorkspacePath(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetWorkspacePath(v)
	})
}

// UpdateWorkspacePath sets the "workspace_path" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateWorkspacePath() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateWorkspacePath()
	})
}

// SetSourceFilePath sets the "source_file_path" field.
func (u *ThreadUpsertOne) SetSourceFilePath(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSourceFilePath(v)
	})
}

// UpdateSourceFilePath sets the "source_file_path" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateSourceFilePath() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSourceFilePath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ThreadUpsertOne) SetCreatedAt(v time.Time) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateCreatedAt() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ThreadUpsertOne) SetLastSyncedAt(v time.Time) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateLastSyncedAt() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// Exec executes the query.
func (u *ThreadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ThreadUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ThreadUpsertOne.ID is not supported by MySQL driver. Use ThreadUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ThreadUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ThreadCreateBulk is the builder for creating many Thread entities in bulk.
type ThreadCreateBulk struct {
	config
	err      error
	builders []*ThreadCreate
	conflict []sql.ConflictOption
}

// Save creates the Thread entities in the database.
func (_c *ThreadCreateBulk) Save(ctx context.Context) ([]*Thread, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Thread, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThreadCreateBulk) SaveX(ctx context.Context) []*Thread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Thread.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadCreateBulk) OnConflict(opts ...sql.ConflictOption) *ThreadUpsertBulk {
	_c.conflict = opts
	return &ThreadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadCreateBulk) OnConflictColumns(columns ...string) *ThreadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadUpsertBulk{
		create: _c,
	}
}

// ThreadUpsertBulk is the builder for "upsert"-ing
// a bulk of Thread nodes.
type ThreadUpsertBulk struct {
	create *ThreadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(thread.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ThreadUpsertBulk) UpdateNewValues() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(thread.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ThreadUpsertBulk) Ignore() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadUpsertBulk) DoNothing() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadCreateBulk.OnConflict
// documentation for more info.
func (u *ThreadUpsertBulk) Update(set func(*ThreadUpsert)) *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ThreadUpsertBulk) SetProvider(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateProvider() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateProvider()
	})
}

// SetOriginalID sets the "original_id" field.
func (u *ThreadUpsertBulk) SetOriginalID(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetOriginalID(v)
	})
}

// UpdateOriginalID sets the "original_id" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateOriginalID() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateOriginalID()
	})
}

// SetTitle sets the "title" field.
func (u *ThreadUpsertBulk) SetTitle(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateTitle() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateTitle()
	})
}

// SetWorkspacePath sets the "workspace_path" field.
func (u *ThreadUpsertBulk) SetWorkspacePath(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetWorkspacePath(v)
	})
}

// UpdateWorkspacePath sets the "workspace_path" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateWorkspacePath() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateWorkspacePath()
	})
}

// SetSourceFilePath sets the "source_file_path" field.
func (u *ThreadUpsertBulk) SetSourceFilePath(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSourceFilePath(v)
	})
}

// UpdateSourceFilePath sets the "source_file_path" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateSourceFilePath() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSourceFilePath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ThreadUpsertBulk) SetCreatedAt(v time.Time) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateCreatedAt() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ThreadUpsertBulk) SetLastSyncedAt(v time.Time) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateLastSyncedAt() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// Exec executes the query.
func (u *ThreadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ThreadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
