// Code generated by ent, DO NOT EDIT.

package thread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/zuhailkhan/threadman/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldProvider, v))
}

// OriginalID applies equality check predicate on the "original_id" field. It's identical to OriginalIDEQ.
func OriginalID(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldOriginalID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldTitle, v))
}

// WorkspacePath applies equality check predicate on the "workspace_path" field. It's identical to WorkspacePathEQ.
func WorkspacePath(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldWorkspacePath, v))
}

// SourceFilePath applies equality check predicate on the "source_file_path" field. It's identical to SourceFilePathEQ.
func SourceFilePath(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSourceFilePath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldCreatedAt, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldLastSyncedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldProvider, v))
}

// OriginalIDEQ applies the EQ predicate on the "original_id" field.
func OriginalIDEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldOriginalID, v))
}

// OriginalIDNEQ applies the NEQ predicate on the "original_id" field.
func OriginalIDNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldOriginalID, v))
}

// OriginalIDIn applies the In predicate on the "original_id" field.
func OriginalIDIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldOriginalID, vs...))
}

// OriginalIDNotIn applies the NotIn predicate on the "original_id" field.
func OriginalIDNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldOriginalID, vs...))
}

// OriginalIDGT applies the GT predicate on the "original_id" field.
func OriginalIDGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldOriginalID, v))
}

// OriginalIDGTE applies the GTE predicate on the "original_id" field.
func OriginalIDGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldOriginalID, v))
}

// OriginalIDLT applies the LT predicate on the "original_id" field.
func OriginalIDLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldOriginalID, v))
}

// OriginalIDLTE applies the LTE predicate on the "original_id" field.
func OriginalIDLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldOriginalID, v))
}

// OriginalIDContains applies the Contains predicate on the "original_id" field.
func OriginalIDContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldOriginalID, v))
}

// OriginalIDHasPrefix applies the HasPrefix predicate on the "original_id" field.
func OriginalIDHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldOriginalID, v))
}

// OriginalIDHasSuffix applies the HasSuffix predicate on the "original_id" field.
func OriginalIDHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldOriginalID, v))
}

// OriginalIDEqualFold applies the EqualFold predicate on the "original_id" field.
func OriginalIDEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldOriginalID, v))
}

// OriginalIDContainsFold applies the ContainsFold predicate on the "original_id" field.
func OriginalIDContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldOriginalID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldTitle, v))
}

// WorkspacePathEQ applies the EQ predicate on the "workspace_path" field.
func WorkspacePathEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldWorkspacePath, v))
}

// WorkspacePathNEQ applies the NEQ predicate on the "workspace_path" field.
func WorkspacePathNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldWorkspacePath, v))
}

// WorkspacePathIn applies the In predicate on the "workspace_path" field.
func WorkspacePathIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldWorkspacePath, vs...))
}

// WorkspacePathNotIn applies the NotIn predicate on the "workspace_path" field.
func WorkspacePathNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldWorkspacePath, vs...))
}

// WorkspacePathGT applies the GT predicate on the "workspace_path" field.
func WorkspacePathGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldWorkspacePath, v))
}

// WorkspacePathGTE applies the GTE predicate on the "workspace_path" field.
func WorkspacePathGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldWorkspacePath, v))
}

// WorkspacePathLT applies the LT predicate on the "workspace_path" field.
func WorkspacePathLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldWorkspacePath, v))
}

// WorkspacePathLTE applies the LTE predicate on the "workspace_path" field.
func WorkspacePathLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldWorkspacePath, v))
}

// WorkspacePathContains applies the Contains predicate on the "workspace_path" field.
func WorkspacePathContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldWorkspacePath, v))
}

// WorkspacePathHasPrefix applies the HasPrefix predicate on the "workspace_path" field.
func WorkspacePathHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldWorkspacePath, v))
}

// WorkspacePathHasSuffix applies the HasSuffix predicate on the "workspace_path" field.
func WorkspacePathHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldWorkspacePath, v))
}

// WorkspacePathEqualFold applies the EqualFold predicate on the "workspace_path" field.
func WorkspacePathEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldWorkspacePath, v))
}

// WorkspacePathContainsFold applies the ContainsFold predicate on the "workspace_path" field.
func WorkspacePathContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldWorkspacePath, v))
}

// SourceFilePathEQ applies the EQ predicate on the "source_file_path" field.
func SourceFilePathEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSourceFilePath, v))
}

// SourceFilePathNEQ applies the NEQ predicate on the "source_file_path" field.
func SourceFilePathNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldSourceFilePath, v))
}

// SourceFilePathIn applies the In predicate on the "source_file_path" field.
func SourceFilePathIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldSourceFilePath, vs...))
}

// SourceFilePathNotIn applies the NotIn predicate on the "source_file_path" field.
func SourceFilePathNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldSourceFilePath, vs...))
}

// SourceFilePathGT applies the GT predicate on the "source_file_path" field.
func SourceFilePathGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldSourceFilePath, v))
}

// SourceFilePathGTE applies the GTE predicate on the "source_file_path" field.
func SourceFilePathGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldSourceFilePath, v))
}

// SourceFilePathLT applies the LT predicate on the "source_file_path" field.
func SourceFilePathLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldSourceFilePath, v))
}

// SourceFilePathLTE applies the LTE predicate on the "source_file_path" field.
func SourceFilePathLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldSourceFilePath, v))
}

// SourceFilePathContains applies the Contains predicate on the "source_file_path" field.
func SourceFilePathContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldSourceFilePath, v))
}

// SourceFilePathHasPrefix applies the HasPrefix predicate on the "source_file_path" field.
func SourceFilePathHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldSourceFilePath, v))
}

// SourceFilePathHasSuffix applies the HasSuffix predicate on the "source_file_path" field.
func SourceFilePathHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldSourceFilePath, v))
}

// SourceFilePathEqualFold applies the EqualFold predicate on the "source_file_path" field.
func SourceFilePathEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldSourceFilePath, v))
}

// SourceFilePathContainsFold applies the ContainsFold predicate on the "source_file_path" field.
func SourceFilePathContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldSourceFilePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldCreatedAt, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldLastSyncedAt, v))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.NotPredicates(p))
}
