// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Thread is the predicate function for thread builders.
type Thread func(*sql.Selector)
